---
- hosts: "masters,workers"
  remote_user: root
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
     - name: create k8s config file
       file:
         path: "/etc/yum.repos.d/k8s.repo"
         state: "touch"

     - name: add k8s repo
       blockinfile:
         path: "/etc/yum.repos.d/k8s.repo"
         block: |
                 [kubernetes]
                 name=Kubernetes
                 baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
                 enabled=1
                 gpgcheck=1
                 repo_gpgcheck=1
                 gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg

     - name: install docker
       shell: |
               yum install -y yum-utils
               yum-config-manager --add-repo https://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
               yum -y install docker-ce-19.03.12-3.el7 docker-ce-cli-19.03.12-3.el7
               systemctl start docker
               systemctl enable docker

     - name: disable swap
       shell: |
               sudo swapoff -a
               sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

     - name: install kubeadm
       shell: |
               yum install -y kubelet-1.19.2 kubectl-1.19.2 kubeadm-1.19.2
               systemctl enable kubelet
               systemctl start kubelet

     - name: disable firewalld
       shell: |
               systemctl stop firewalld.service
               systemctl disable firewalld.service
