- hosts: masters
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --kubernetes-version=1.19.2 --image-repository registry.aliyuncs.com/google_containers --service-cidr=10.10.0.0/16 --pod-network-cidr=10.122.0.0/16

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0777

    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
      args:
        chdir: $HOME

    - name: master node setting
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-

    - name: get the token for joining the worker nodes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: debug
      debug: msg="{{ kubernetes_join_command.stdout }}"

    - name: copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777

    - name: fetch admin.conf to ansible's server
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: /home
